name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    uses: actions/checkout@v3
  steps:
  - name: Build the Docker image
  - run: docker-compose -f docker-compose-build.yaml build --parallel
  - run: docker tag udagram-api-feed sixtyfive0/udagram-api-feed:v2
  - run: docker tag udagram-api-user sixtyfive0/udagram-api-user:v2
  - run: docker tag udagram-frontend:local sixtyfive0/udagram-frontend:v2
  - run: docker tag udagram-reverseproxy sixtyfive0/udagram-reverseproxy:v2
  - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
  - run: docker push sixtyfive0/udagram-api-feed:v2
  - run: docker push sixtyfive0/udagram-api-user:v2
  - run: docker push sixtyfive0/udagram-frontend:v2
  - run: docker push sixtyfive0/udagram-reverseproxy:v2
